server:
  host: "0.0.0.0"  # 监听所有网卡，便于手机/其他设备通过局域网 IP 访问
  port: ":8090"    # 兼容旧格式，支持写成 ":8090" 或只写 "8090"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "123456"
  dbname: "alice"
  sslmode: "disable"

jwt:
  secret_key: "alice-jwt-secret-key-2025"
  expires_in: 24  # hours

log:
  level: "info"

minio:
  endpoint: "localhost:9000"
  access-key: "WdVQCeGkKBi1eeIoXVLZ"
  secret-key: "BnAAO63lz1ExyJqqO7bM44e1fTo14Nl6ziRjioBf"
  use-ssl: false
  base-url: "http://192.168.64.1:9000"  # 可选，若配置则返回文件 URL 使用该域名
  max-file-size-mb: 20
  allowed-mime-types:
  # 使用通配符 * 放开所有类型（开发环境）。生产请改成精确或前缀如 image/* 等。
  - "*"
  enable-virus-scan: false  # 钩子示例（需自行集成扫描引擎）
